apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane-core
spec:
  releaseName: crossplane-core
  interval: 5m
  chart:
    spec:
      chart: stable
      version: '1.4.1'
      sourceRef:
        kind: HelmRepository
        name: crossplane-repository
        namespace: flux-system
      interval: 1m


