---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: application-s3reader
  namespace: flux-system
spec:
  dependsOn:
  - name: application-recommender
  interval: 30s
  path: ./deploy/crossplane-applications/s3reader
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: crossplane-addon-cluster-connection    
  healthChecks:
  - kind: Deployment
    name: s3-reader
    namespace: nodejs      
  validation: client
