---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application-init.yaml
  # - application-external-secrets-controller.yaml
  # - application-external-secrets.yaml
  # - application-sealed-secrets-controller.yaml
  # - application-flux-toolkit.yaml
  # - application-flux-sync.yaml
   		
	
