---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crossplane-helmrelease.yaml
  - crossplane-aws-provider-package.yaml
  - crossplane-k8s-provider-package.yaml
  - crossplane-configuration-package.yaml
  - crossplane-composite-resources.yaml
  