---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 2-sealed-secrets-controller.yaml
  - 3-aws-credentials-sealed.yaml
  - 4-aws-provider.yaml
  - 5-aws-providerconfig.yaml


